version: "3.9"
services:
  web:
    image: "agavrilov01/spring-boot-demo"
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    user: root
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
      - ./data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    ports:
      - 9100:9100

  cadvisor:
    image: google/cadvisor:latest
    container_name: monitoring_cadvisor
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    user: root
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
